export const readableArticleBlocks: Record<string, string[]> = {
  "reno-township": [
    "Reno Township, Iosco County, Michigan",
    "Located in the northwestern interior of Reno Township, this rural community developed from dense forest into a quiet agricultural and residential township. Its story reflects lumbering roots, family farms, and long-standing local traditions.",
    "1870 – 1890: Foundations in the Forest",
    "Reno Township was officially organized in 1875, during the height of Michigan’s lumber boom. Early settlers arrived from New York, Canada, and other eastern states, drawn by the vast pine forests that covered the region. Logging camps dominated the landscape, with timber transported to mills in nearby East Tawas and Tawas City.",
    "Families such as the Bells, Pringles, and Whittemores began carving out homesteads, clearing land by hand and building the township’s first permanent roots.",
    "1890 – 1910: Railroads and Expanding Settlement",
    "By the 1890s, railroads began pushing into the region, linking Reno Township to nearby communities such as Hale. As timber resources declined, settlers turned to farming. Small family farms replaced cutover land, producing hay, potatoes, and livestock.",
    "One-room schoolhouses and small churches became central to daily life, serving a scattered but growing population.",
    "1910 – 1930: Establishing an Agricultural Community",
    "With the lumber era fading, agriculture became the township’s backbone. Families like the Johnsons, Smiths, and Swansons developed stable farms across the area. Improved roads strengthened connections to Whittemore and other parts of Iosco County.",
    "Despite isolation, the community grew more organized, with schools, churches, and local cooperation shaping township identity.",
    "1930 – 1950: Hardship and Resilience",
    "The Great Depression brought economic hardship to Reno Township. Many residents relied on subsistence farming, hunting, and shared resources to survive. Federal programs helped improve roads and infrastructure. During World War II, local residents contributed both through military service and agricultural production at home.",
    "The postwar years brought slow recovery and renewed stability.",
    "1950 – 1970: Modernization Reaches the Township",
    "The postwar decades introduced electricity, improved roads, and increased mobility. While agriculture remained important, residents began commuting to nearby towns for work. Community life centered around churches, schools, and seasonal gatherings. The rural landscape—farms, woodlots, and open land—remained largely unchanged.",
    "1970 – 1990: Transition and Changing Land Use",
    "As farming declined, some land returned to forest while other areas became rural homesites. Reno Township increasingly served as a quiet residential area for those working in nearby communities like Oscoda. Outdoor recreation—hunting, fishing, and access to nearby lakes and forests—became more important to the township’s identity.",
    "1990 – 2010: A Blend of Old and New",
    "By the late 20th century, Reno Township was home to both multi-generation families and newcomers seeking a rural lifestyle. Agriculture continued on a smaller scale, while improved roads and communication allowed residents to remain connected to surrounding areas without losing the township’s quiet character.",
    "Interest in local history grew, with efforts to preserve cemeteries, family records, and early settlement stories.",
    "2010 – Present: Preserving Rural Heritage",
    "Today, Reno Township remains a peaceful rural community rooted in its past. While development has remained limited, its identity continues to be shaped by its early logging history and agricultural traditions. Residents value open land, natural surroundings, and a slower pace of life.",
    "Its proximity to Hale and the Lake Huron shoreline communities provides access to services while maintaining its distinctly rural character. The preservation of historic sites, cemeteries, and family histories ensures that Reno Township’s story continues to be passed down to future generations."
  ],
  "tawas-township": [
    "Tawas Township: A 20-Year Chronicle (1850s–Present)",
    "1850s–1870s: First Settlement and Wilderness Clearing",
    "Tawas Township began as heavily forested land dominated by white pine, cedar, and hardwoods. Following the arrival of James A. Jackson in 1852, settlement slowly spread inland as pioneers claimed land for homesteads. Early residents lived in crude log structures and depended on hunting, fishing, and subsistence farming.",
    "The first trails were little more than widened footpaths used for hauling supplies and timber. Logging crews began cutting accessible stands of pine, marking the township’s earliest economic activity.",
    "1870s–1890s: Logging Camps and Land Development",
    "During the peak lumber years, Tawas Township was dotted with logging camps and temporary settlements. Lumber operations, influenced by regional figures such as David D. Oliver, expanded into the township’s interior forests. Timber was cut in winter and hauled by sled to staging areas. As land was cleared, it was often sold or repurposed for farming.",
    "Early roads began forming along section lines, and small family farms emerged where dense forest once stood. Life remained rugged, with isolation and hard labor defining daily existence.",
    "1890s–1910s: From Timber to Agriculture",
    "With most marketable pine removed, the township entered a period of transition. Abandoned logging lands were converted into farms, though the sandy soil and short growing season made agriculture challenging. Settlers raised hardy crops such as potatoes, oats, and hay, along with small livestock.",
    "Communities became more stable, with the establishment of one-room schoolhouses and informal gathering places. Rural life centered on family labor, seasonal cycles, and cooperation among neighbors.",
    "1910s–1930s: Rural Life and Economic Strain",
    "Agriculture remained the primary livelihood, though many residents supplemented income through seasonal work in lumber remnants or nearby industries. Roads gradually improved, but much of the township remained difficult to access, especially in winter and spring.",
    "The Great Depression brought significant hardship—crop prices fell, jobs were scarce, and many families relied on self-sufficiency to survive. Despite this, most farms remained occupied, and the township’s population held steady.",
    "1930s–1950s: New Deal Era and Land Use Changes",
    "During and after the Depression, some marginal farmland was abandoned and gradually returned to forest. Government programs and changing land use patterns helped reshape parts of the township. Improved road systems and rural electrification began reaching more homes, transforming daily life.",
    "Small-scale logging of second-growth timber continued, alongside farming. Outdoor recreation—particularly hunting and fishing—became more common, both for subsistence and leisure.",
    "1950s–1970s: Rural Modernization and Residential Growth",
    "Postwar prosperity brought noticeable change. Better roads, automobiles, and modern conveniences made rural living more accessible. Farms began to decline in number as some land was sold or divided. New homes were built, including seasonal residences used during warmer months.",
    "Electricity, improved heating, and modern equipment changed how residents lived and worked. The township gradually shifted from purely agricultural toward a mix of rural and residential use.",
    "1970s–1990s: Transition to a Residential Township",
    "By the late 20th century, Tawas Township had evolved into a primarily residential area. Many residents commuted for work, while others were retirees or seasonal homeowners. Open land and forest remained important features, but subdivisions and housing developments increased.",
    "Local roads were improved and maintained year-round, and access to services became more reliable. The township balanced growth with its rural character.",
    "1990s–2010s: Steady Growth and Infrastructure Expansion",
    "The township continued to grow at a measured pace. New housing developments expanded into previously undeveloped areas, while older farms were repurposed or divided. Infrastructure improvements—including road maintenance, utilities, and emergency services—supported a larger and more diverse population.",
    "The area remained attractive for those seeking quiet living with access to natural surroundings.",
    "2010s–Present: Modern Rural Community",
    "Today, Tawas Township is a stable residential community characterized by wooded landscapes, open space, and a mix of year-round and seasonal residents. While agriculture and logging no longer dominate, the land still reflects those earlier uses.",
    "The township continues to attract people looking for a quieter lifestyle, with ongoing development balanced by its rural setting.",
    "Legacy",
    "From dense pine forests and isolated logging camps to farms, and finally to a modern residential township, Tawas Township has continually adapted to changing economic and social conditions. Its history is defined by the people who carved a living from the land and shaped a community rooted in resilience and independence."
  ],
  "save-our-museum": [
    "WHY SUPPORT IS NEEDED",
    "As a non-profit organization, the Museum relies on the generosity of our members and guests to sustain our operations. With just under $100,000 in our fund balance we have only four years of operating cash flow remaining. The time is now. We must develop a better funding approach to ensure long-term sustainability of the Museum or we will be forced to close our doors – a path we feel is unacceptable.",
    "CAMPAIGN GOAL",
    "To ensure our doors stay open, the losco County Historical Society has kicked off a Save Our Museum Campaign to raise $290,000 in endowed gifts over the next five years. With a restricted spending policy on these endowed gifts, this will give the Museum an annual income of $5,000 in its first year to nearly $20,000 in its fifth year. And, our future just got a whole lot brighter!",
    "MAKE A LASTING GIFT",
    "We invite you to join us in making a campaign gift to help ensure a future for our past and continue inspiring audiences of all ages and interests with our local legacy of family, community and commerce. By contributing to the endowment fund today, your generosity will keep giving to the Museum and our community forever.",
    "CAMPAIGN INFORMATION",
    "For more information on the Campaign, click on the Endowment Campaign Brochure below or call the Museum at 989-362-8911. Thank you for helping Save Our Museum!",
    "CAMPAIGN BROCHURE",
    "Endowment Campaign Brochure — File Size: 2558 kb; File Type: pdf. Download File",
    "PLEDGE INFORMATION",
    "To make your pledge online, please click here (A new page will open to the Community Foundation for Northeast Michigan where you may confidently and securely make your contribution to the endowment fund.) The pledge card, shown below, is simple and easy to complete!",
    "Use the link at the bottom of the page to download and print your pledge card today!",
    "PLEDGE CARD",
    "Pledge Card — File Size: 509 kb; File Type: pdf. Download File"
  ]
};
